# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    vsVersion: '16.0'
    clean: true
- task: VSTest@2
  inputs:
    testSelector: 'testRun'
    searchFolder: '$(System.DefaultWorkingDirectory)'
    codeCoverageEnabled: true
- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/CSRedis.csproj'
    versioningScheme: 'off'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'sink'
    publishLocation: 'Container'